/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDVRegularEstado.java
 *
 * Created on 23/10/2012, 11:16:43 AM
 */

package com.softcommerce.gui;

import com.softcommerce.entity.ControlDoc;
import com.softcommerce.logic.LogicControlDoc;
import com.softcommerce.tablemodel.TableModelDVRegular;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class FormDVRegularEstado extends javax.swing.JPanel {
    private java.net.URL path;
    /** Creates new form FormDVRegularEstado */
    public FormDVRegularEstado(java.net.URL pathConect) {
        try {
            path = pathConect;
            initComponents();
            init();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (InstantiationException ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardarTodo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnGuardarXDocumento = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(850, 400));
        setPreferredSize(new java.awt.Dimension(850, 400));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(tablaDatos);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnGuardarTodo.setText("Regularizar Documento");
        btnGuardarTodo.setFocusable(false);
        btnGuardarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarTodo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTodoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardarTodo);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnGuardarXDocumento.setText("Regularizar Todo");
        btnGuardarXDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarXDocumentoActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardarXDocumento);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarXDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarXDocumentoActionPerformed
        try {
            LogicControlDoc log = new LogicControlDoc(path);
            JOptionPane.showMessageDialog(null, log.regularizarEstadoDocAtendido());;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (InstantiationException ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        tableModelDVRegular.fireTableDataChanged();
    }//GEN-LAST:event_btnGuardarXDocumentoActionPerformed

    private void btnGuardarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTodoActionPerformed
    int fila = tablaDatos.getSelectedRow();
        if (fila != -1) {
                int modelrow = tablaDatos.convertRowIndexToModel(fila);
                ControlDoc bean = ((TableModelDVRegular) tablaDatos.getModel()).getValue(modelrow);
                LogicControlDoc log=new LogicControlDoc(path);
            try {
                JOptionPane.showMessageDialog(null, log.regularizarEstadoXDocAtendido(bean.getIdTipoDoc(), bean.getSeriedoc(), bean.getPreimpresodoc()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (InstantiationException ex) {
                Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (IllegalAccessException ex) {
                Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(FormDVRegularEstado.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
                tableModelDVRegular.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            tablaDatos.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarTodoActionPerformed

    private void init() throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception{
        tableModelDVRegular=new TableModelDVRegular();
        LogicControlDoc log=new LogicControlDoc(path);
        tableModelDVRegular.setData(log.listarRegularizarEstadoDocAtendido());
        tablaDatos.setModel(tableModelDVRegular);
        tablaDatos.setAutoCreateRowSorter(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarTodo;
    private javax.swing.JButton btnGuardarXDocumento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
    private TableModelDVRegular tableModelDVRegular;
}
