/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPanelUA.java
 *
 * Created on 08/11/2012, 02:26:43 PM
 */

package com.softcommerce.gui;

import com.softcommerce.beans.Usuario;
import com.softcommerce.entity.AutorizarCorrelativo;
import com.softcommerce.logic.LogicAutorizaCorrelativo;
import com.softcommerce.tablemodel.TableModelAutorizaCorrelativo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Team Develtrex
 */
public class FormPanelUA extends javax.swing.JDialog {
    private java.net.URL path;
    private Usuario bean;
    /** Creates new form FormPanelUA */
    public FormPanelUA(java.awt.Frame parent, boolean modal, java.net.URL ruta, Usuario beanUsuario) {
        super(parent, modal);
        try {
            path = ruta;
            bean = beanUsuario;
            initComponents();
            init();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (InstantiationException ex) {
            Logger.getLogger(FormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(FormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnActivar.setText("Activar");
        btnActivar.setFocusable(false);
        btnActivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActivar);

        btnDesactivar.setText("Desactivar");
        btnDesactivar.setFocusable(false);
        btnDesactivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesactivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDesactivar);
        jToolBar1.add(jSeparator1);

        jLabel1.setText("Trabajador: ");
        jToolBar1.add(jLabel1);

        lblNombres.setText("Apellidos y Nombres del Trabajador");
        jToolBar1.add(lblNombres);
        jToolBar1.add(jSeparator2);

        jLabel3.setText("Usuario: ");
        jToolBar1.add(jLabel3);

        lblUsuario.setText("Nombre de Usuario");
        jToolBar1.add(lblUsuario);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        tableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableDatos);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception{
        lblNombres.setText(bean.getTrabajador());
        lblUsuario.setText(bean.getNombre());
        modelTable=new TableModelAutorizaCorrelativo();
        tableDatos.setModel(modelTable);
        loadTable();
    }

    public  void loadTable() throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception{
        modelTable.setData((new LogicAutorizaCorrelativo(path)).listar(bean.getId_usuario()));
        modelTable.fireTableDataChanged();
    }
    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
      FormUA form=new FormUA(this,true,path,bean);
      form.setTitle("Autorizar Series");
      form.setLocationRelativeTo(null);
      form.setVisible(true);
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        int fila = tableDatos.getSelectedRow();
        if (fila != -1) {
            try {
                int modelrow = tableDatos.convertRowIndexToModel(fila);
                AutorizarCorrelativo beanAC = ((TableModelAutorizaCorrelativo) tableDatos.getModel()).getValue(modelrow);
                java.util.Date fechafin = new java.util.Date();
                beanAC.setFechaFin(new java.sql.Date(fechafin.getTime()));
                beanAC.setEstado("D");
                beanAC.setTipoOperacion("A");                                                
                JOptionPane.showMessageDialog(null, (new LogicAutorizaCorrelativo(path)).mantenimiento(beanAC));                
                loadTable();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (InstantiationException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (IllegalAccessException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            tableDatos.requestFocus();
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tableDatos;
    // End of variables declaration//GEN-END:variables
    private TableModelAutorizaCorrelativo modelTable;
}
