/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UiFormUA.java
 *
 * Created on 08/11/2012, 03:37:41 PM
 */

package com.softcommerce.views.uiformua;


import com.softcommerce.gui.*;
import com.softcommerce.beans.Usuario;
import com.softcommerce.comboboxmodel.ComboModelCorrelativo;
import com.softcommerce.comboboxmodel.ComboModelPuntoVenta;
import com.softcommerce.comboboxmodel.ComboModelTipoDoc;
import com.softcommerce.entity.AutorizarCorrelativo;
import com.softcommerce.entity.PuntoVenta;
import com.softcommerce.entity.TipoDocVenta;
import com.softcommerce.logic.LogicAutorizaCorrelativo;
import com.softcommerce.logic.LogicCorrelativo;
import com.softcommerce.logic.LogicPuntoVenta;
import com.softcommerce.logic.LogicTipoDocumentoVenta;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Team Develtrex
 */
public class UiFormUA extends javax.swing.JDialog  implements InterUiFormUA {
    protected java.net.URL path;
    protected Usuario bean;
    protected FormPanelUA formPadre;
    /** Creates new form UiFormUA */
    public UiFormUA(java.awt.Dialog parent, boolean modal,java.net.URL ruta, Usuario beanUsuario) {
        super(parent, modal);
        try {
            formPadre=(FormPanelUA)parent;
            path = ruta;
            bean = beanUsuario;
            initComponents();
            init();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UiFormUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (InstantiationException ex) {
            Logger.getLogger(UiFormUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IllegalAccessException ex) {
            Logger.getLogger(UiFormUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(UiFormUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        cbPuntoVenta = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbSerie = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtcorrelativo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Punto de Venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cbPuntoVenta, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tipo de Documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cbTipoDocumento, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Serie");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(cbSerie, gridBagConstraints);

        jLabel4.setText("Id Correlativo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        txtcorrelativo.setEditable(false);
        txtcorrelativo.setMinimumSize(new java.awt.Dimension(80, 20));
        txtcorrelativo.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtcorrelativo, gridBagConstraints);

        jLabel5.setText("Fecha de Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        btnAction.setText("Guardar");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnAction, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnActionActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_btnActionActionPerformed

    protected void init() throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnAction;
    protected javax.swing.JComboBox cbPuntoVenta;
    protected javax.swing.JComboBox cbSerie;
    protected javax.swing.JComboBox cbTipoDocumento;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JTextField txtcorrelativo;
    // End of variables declaration//GEN-END:variables
     protected JDateChooser dc_fechainicio;
     protected ComboModelPuntoVenta cbModelPV;
     protected ComboModelTipoDoc cbModelTipoDoc;
     protected ComboModelCorrelativo cbModelCorrelativo;

     ItemListener itemListener=new ItemListener(){

        @Override
        public void itemStateChanged(ItemEvent e) {
            if(cbPuntoVenta.equals(e.getSource())){
                txtcorrelativo.setText(null);
                loadCorrelativo();
            }else if(cbTipoDocumento.equals(e.getSource())){                
                txtcorrelativo.setText(null);
                loadCorrelativo();
            }else if(cbSerie.equals(e.getSource())){
                try{
                txtcorrelativo.setText(((ComboModelCorrelativo) cbSerie.getModel()).getElement(cbSerie.getSelectedIndex()).getIdCorrelativo());
                }catch(ArrayIndexOutOfBoundsException ex){
                    System.out.println(ex.getMessage());
                }
            }
        }

     };

     protected void loadCorrelativo() {
    }
}
