/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UiFormPanelUA.java
 *
 * Created on 08/11/2012, 02:26:43 PM
 */

package com.softcommerce.views.uiformpanelua;


import com.softcommerce.gui.*;
import com.softcommerce.beans.Usuario;
import com.softcommerce.entity.AutorizarCorrelativo;
import com.softcommerce.logic.LogicAutorizaCorrelativo;
import com.softcommerce.tablemodel.TableModelAutorizaCorrelativo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Team Develtrex
 */
public class UiFormPanelUA extends javax.swing.JDialog  implements InterUiFormPanelUA {
    protected java.net.URL path;
    protected Usuario bean;
    /** Creates new form UiFormPanelUA */
    public UiFormPanelUA(java.awt.Frame parent, boolean modal, java.net.URL ruta, Usuario beanUsuario) {
        super(parent, modal);
        try {
            path = ruta;
            bean = beanUsuario;
            initComponents();
            init();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UiFormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (InstantiationException ex) {
            Logger.getLogger(UiFormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (IllegalAccessException ex) {
            Logger.getLogger(UiFormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(UiFormPanelUA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnActivar.setText("Activar");
        btnActivar.setFocusable(false);
        btnActivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActivar);

        btnDesactivar.setText("Desactivar");
        btnDesactivar.setFocusable(false);
        btnDesactivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesactivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDesactivar);
        jToolBar1.add(jSeparator1);

        jLabel1.setText("Trabajador: ");
        jToolBar1.add(jLabel1);

        lblNombres.setText("Apellidos y Nombres del Trabajador");
        jToolBar1.add(lblNombres);
        jToolBar1.add(jSeparator2);

        jLabel3.setText("Usuario: ");
        jToolBar1.add(jLabel3);

        lblUsuario.setText("Nombre de Usuario");
        jToolBar1.add(lblUsuario);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        tableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableDatos);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void init() throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception{
        lblNombres.setText(bean.getTrabajador());
        lblUsuario.setText(bean.getNombre());
        modelTable=new TableModelAutorizaCorrelativo();
        tableDatos.setModel(modelTable);
        loadTable();
    }

    public  void loadTable() throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception {
    }
    protected void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
      FormUA form=new FormUA(this,true,path,bean);
      form.setTitle("Autorizar Series");
      form.setLocationRelativeTo(null);
      form.setVisible(true);
    }//GEN-LAST:event_btnActivarActionPerformed

    protected void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_btnDesactivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnActivar;
    protected javax.swing.JButton btnDesactivar;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JToolBar.Separator jSeparator1;
    protected javax.swing.JToolBar.Separator jSeparator2;
    protected javax.swing.JToolBar jToolBar1;
    protected javax.swing.JLabel lblNombres;
    protected javax.swing.JLabel lblUsuario;
    protected javax.swing.JTable tableDatos;
    // End of variables declaration//GEN-END:variables
    protected TableModelAutorizaCorrelativo modelTable;
}
