/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPanelConfigItem.java
 *
 * Created on 27/09/2012, 11:43:42 AM
 */
package com.softcommerce.views.uiformpanelconfigpadronproveedor;


import com.softcommerce.gui.*;
import com.softcommerce.beans.Anexo;
import com.softcommerce.entity.PadronProveedor;
import com.softcommerce.formularios.RegisterProveedor;
import com.softcommerce.logic.LogicPadronProveedor;
import com.softcommerce.tablemodel.TableModelConfigPadronProveedor;
import com.softcommerce.util.render.CellRendererImageEstado;
import com.softcommerce.util.Propiedad;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class UiFormPanelConfigPadronProveedor extends javax.swing.JPanel  implements InterUiFormPanelConfigPadronProveedor {

    protected JDialog dialog;
    protected FormConfigPadronProveedor formConfigPadron;
    protected RegisterProveedor padre;   
    protected Anexo beanAnexo;

    /**
     * Creates new form FormPanelConfigItem
     */
    public UiFormPanelConfigPadronProveedor(JDialog framePadre) {
        padre = (RegisterProveedor) framePadre;
        initComponents();
        init();
    }

    protected void init() {
        tableModelConfigPadron = new TableModelConfigPadronProveedor();
        tablaDatos.setModel(tableModelConfigPadron);
        tablaDatos.getColumnModel().getColumn(0).setCellRenderer(new CellRendererImageEstado());
        btnActivar.addActionListener(actionListener);
    }
    ActionListener actionListener = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            if (ae.getSource().equals(btnActivar)) {
                dialog = new JDialog(padre);
                String codigoAnexo = padre.getTxt_Codigo().getText();
                formConfigPadron = new FormConfigPadronProveedor(codigoAnexo,padre);
                dialog.getContentPane().add(formConfigPadron);
                dialog.pack();
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        pnlBarraHerramientas = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDatos.setLayout(new java.awt.BorderLayout());

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        pnlDatos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlDatos, java.awt.BorderLayout.CENTER);

        pnlBarraHerramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBarraHerramientas.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnActivar.setText("Activar");
        btnActivar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActivar.setFocusable(false);
        btnActivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnActivar);

        btnDesactivar.setText("Desactivar");
        btnDesactivar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesactivar.setFocusable(false);
        btnDesactivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesactivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDesactivar);

        pnlBarraHerramientas.add(jToolBar1, java.awt.BorderLayout.CENTER);

        add(pnlBarraHerramientas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    protected void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_btnDesactivarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnActivar;
    protected javax.swing.JButton btnDesactivar;
    protected javax.swing.JButton jButton1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JToolBar jToolBar1;
    protected javax.swing.JPanel pnlBarraHerramientas;
    protected javax.swing.JPanel pnlDatos;
    protected javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
    protected TableModelConfigPadronProveedor tableModelConfigPadron;

    public Anexo getBeanAnexo() {
        return beanAnexo;
    }

    public void setBeanAnexo(Anexo paramBeanAnexo) {
    }

    public TableModelConfigPadronProveedor getTableModelConfigPadron() {
        return tableModelConfigPadron;
    }
    
    
}
